modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
issueTrackerURL = "https://github.com/liopyu/AnimationJS/issues" #optional
[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
[[mods]] #mandatory
modId = "animationjs" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
credits = "Liopyu" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
[[dependencies.animationjs]] #optional
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.animationjs]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.animationjs]]
modId = "kubejs"
mandatory = true
versionRange = "[2100.7.0-build.83,)"
ordering = "NONE"
side = "BOTH"
[[mixins]]
config = "animationjs.mixins.json"